title: Sebastian Wette
email: mail@sebastianwette.de
description: >- 
  This is the GitHub user-page of me, Sebastian Wette.
  It is used to host a short bio as well as a blog about the current work I do.
  There is also a section about useful resources that I came across, that may be useful to some people :)
baseurl: "" 
url: "https://sebiwtt.github.io" 
twitter_username: sebiwette
github_username: sebiwtt

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/sebiwtt" }
    - { platform: twitter, user_url: "https://twitter.com/sebiwette" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/sebastian-wette-8292211b0/"
      }

header_pages:
  - Resources.md  
  - Bio.md
  
author:
  name: Sebastian Wette
  email: "mail@sebastianwette.de"

theme: minima
plugins:
  - jekyll-feed

